/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jinxos_AwesomeScript_ProcessChecker */

#ifndef _Included_de_jinxos_AwesomeScript_ProcessChecker
#define _Included_de_jinxos_AwesomeScript_ProcessChecker
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jinxos_AwesomeScript_ProcessChecker
 * Method:    IsRunning
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_jinxos_AwesomeScript_ProcessChecker_IsRunning
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
