/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jinxos_AwesomeScript_MemoryWriter */

#ifndef _Included_de_jinxos_AwesomeScript_MemoryWriter
#define _Included_de_jinxos_AwesomeScript_MemoryWriter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jinxos_AwesomeScript_MemoryWriter
 * Method:    GetBaseAddress
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_jinxos_AwesomeScript_MemoryWriter_GetBaseAddress
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_jinxos_AwesomeScript_MemoryWriter
 * Method:    ReadMemory
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_de_jinxos_AwesomeScript_MemoryWriter_ReadMemory
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     de_jinxos_AwesomeScript_MemoryWriter
 * Method:    WriteMemory
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_de_jinxos_AwesomeScript_MemoryWriter_WriteMemory
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     de_jinxos_AwesomeScript_MemoryWriter
 * Method:    OpenTask
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_jinxos_AwesomeScript_MemoryWriter_OpenTask
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_jinxos_AwesomeScript_MemoryWriter
 * Method:    CloseTask
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_jinxos_AwesomeScript_MemoryWriter_CloseTask
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_jinxos_AwesomeScript_MemoryWriter
 * Method:    ProtectMemory
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_de_jinxos_AwesomeScript_MemoryWriter_ProtectMemory
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     de_jinxos_AwesomeScript_MemoryWriter
 * Method:    GetLastError
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_jinxos_AwesomeScript_MemoryWriter_GetLastError
  (JNIEnv *, jclass);

/*
 * Class:     de_jinxos_AwesomeScript_MemoryWriter
 * Method:    AllocateBytes
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_de_jinxos_AwesomeScript_MemoryWriter_AllocateBytes
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     de_jinxos_AwesomeScript_MemoryWriter
 * Method:    AllocateMemory
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_jinxos_AwesomeScript_MemoryWriter_AllocateMemory
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_jinxos_AwesomeScript_MemoryWriter
 * Method:    GetBytes
 * Signature: (II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_de_jinxos_AwesomeScript_MemoryWriter_GetBytes
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
