/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_jinxos_AwesomeScript_KeyPress */

#ifndef _Included_de_jinxos_AwesomeScript_KeyPress
#define _Included_de_jinxos_AwesomeScript_KeyPress
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_jinxos_AwesomeScript_KeyPress
 * Method:    IsPressed
 * Signature: (I)V
 */
JNIEXPORT jboolean JNICALL Java_de_jinxos_AwesomeScript_KeyPress_IsPressed
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
